### ISSUE TITLE
renderthreads wont run

### ISSUE THREAD

**Issue by andrewdyn** [timmwagener/renderthreads#4]
Hello,
after running script like it said in doc Nuke gives some errors
# Result: Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "c:/home//.nuke/python\renderthreads\renderthreads.py", line 89, in <module>
    from lib import renderthreads_render
  File "c:/home/.nuke/python\renderthreads\lib\renderthreads_render.py", line 45, in <module>
    class RenderCommand(QtCore.QObject):
  File "c:/home/.nuke/python\renderthreads\lib\renderthreads_render.py", line 54, in RenderCommand
    sgnl_readd_job = QtCore.Signal(RenderCommand, int)
NameError: name 'RenderCommand' is not defined

OS - Windows
Nuke 8.0v6

**Comment by timmwagener** [comment]
Hey Andrew,

that is related to a feature i built in yesterday. Thanks for the bug report.
I enabled a download of version 0.2.8, for an immediate fix, here:
https://pypi.python.org/pypi/renderthreads/0.2.8
Hope that helps for now. Will be on it to fix that issue......strange though that it didnt appear when testing here.

**Comment by timmwagener** [comment]
Hey Andrew,
i published a new version (0.3.1) in order to fix this bug. I recommend to replace 0.2.8 with it, in case you downloaded it. Please let me know if the bug is fixed and the issue can be closed, thanks.

**Comment by andrewdyn** [comment]
Yes, 0.3.1. fixed it, thank you.

**Comment by timmwagener** [comment]
Great :D
