### ISSUE TITLE
Repeat errors (too rigid timeout settings)

### ISSUE THREAD

**Issue by gianne** [timmwagener/renderthreads#5]
Hey Timm,

Been getting errors; basically unable to render any frames out, even for scripts that renders quickly. Log message says, "Process terminated, maybe because of a too rigid timeout setting."

Have tried maxing the timeout value or/and reducing the number of threads, and reinstalling it according to the docs, but the error remains the same. 

OS: Windows
Nuke 9.0v1

**Comment by timmwagener** [comment]
Hi gianne,

i just tested renderthreads with Nuke 9.0v1 and 9.0v3 on Windows. I could not reproduce the problems you are describing.

## Things you could check:
- Try to use the same command line that is displayed in renderthreads cmd. line menu with a real command line and see if Nuke executes successfully. If it doesnt execute successfully, there is also a good chance, that you will get a meaningfull error message.
- Are you using some more exotic command line flags from the menu? The renderthreads command line menu exposes all flags for Nuke8 command line rendering, maybe some of them dont work in Nuke9. Or maybe you checked some command line flags that are not compatible?
- The log should display the return code for the process that crashed or didnt execute at all along with the error msg. The return code has a meaning. Maybe you could post a screenie that shows the renderthreads log with the error messages.

![nuke_9_test_1_tw](https://cloud.githubusercontent.com/assets/2694225/6437929/9b3d980a-c0c4-11e4-9261-265e8068037c.jpg)
![nuke_9_test_2_tw](https://cloud.githubusercontent.com/assets/2694225/6437930/9b3e0a7e-c0c4-11e4-9d08-572d5feceeeb.jpg)

**Comment by gianne** [comment]
Hi Timm,

Thanks for the quick reply & apologies for the delay. An update from my side:

1) Command prompt: There is an issue with the init.py file; removed the comma at the problematic line, but no bite. This is only a quick try, and will try to solve it. Also, noticed in Renderthreads > Command Line; there are random spaces in the file location line. Unsure if this is an issue. 

2) Command line flags: Will fix the issue above first before trying this. Currently using the default settings.

Here's a screenshot:

![renderthread_ts](https://cloud.githubusercontent.com/assets/11263828/6592015/e70e89a2-c802-11e4-8a20-5c1f9459ee15.jpg)

Cheers,
gianne

**Comment by timmwagener** [comment]
Hey gianne,

> 1) Command prompt: There is an issue with the init.py file; removed the comma at the problematic line, but no bite. This is only a quick try, and will try to solve it. Also, noticed in Renderthreads > Command Line; there are random spaces in the file location line. Unsure if this is an issue.

The random spaces in the displayed command line are not an issue. I introduce them explicitly only in the string that is shown in the interface to enable PyQT to split longer strings.

> 2) Command line flags: Will fix the issue above first before trying this. Currently using the default settings.

Sure, let me know if you were able to work it out. There is a big chance that as soon as you are able to launch a render from the command line manually, you can launch it successfully from **renderthreads** too.

BTW the error you are getting there in the console says **Runtime Error: Not in GUI mode**. There is a flag to explicitly force Nuke to start in GUI mode, i believe it's **--tg** (stands for terminal GUI i guess). Not sure if this solves your problem though. It surely would be better to have the init.py set up in a way that it performs under all circumstances.

**Comment by gianne** [comment]
Hey Timm,

Apologies for the late feedback; work ramped up and couldn't test it until now.

The main issue seems to be the init.py file. Problem was the GUI related lines. These lines ought to be in menu.py instead. Fixed it, tried it, didn't work, then restarted the computer, and now it is working well. 

Tried utilising the --tg, but all the launches end up not responding. But this was only utilised due to prev problem; not an issue after the init.py fix.

Thanks for the help and tips!

**Comment by timmwagener** [comment]
Hey Gianne,

glad to hear it's working for you now. Thanks for letting me know.

Cheers,
Timm
