### ISSUE TITLE
Enhancement | Display render shell off (standard)

### ISSUE THREAD

**Issue by alexanderrichtertd** [timmwagener/renderthreads#9]
It´s easier to use if an artist isn´t confused by the many windows which appear.

Maybe relocate it to make it more clearly:
Possible unter Render\Log at the bottom

Greetings, Alex

**Comment by timmwagener** [comment]
Hey Alex, thanks for your feedback but i already made an issue on that myself yesterday :) Will close the other and keep this one.
I have some stuff to do right now with priority (update my portfolio only and write some applications), but once that is done, i will install Nuke again and surely go about updating renderthreads!
Cheers, Timm

PS: The labels feature on the right gives you colored tags for bugs, enhancements etc.

**Comment by alexanderrichtertd** [comment]
No rush I had just burst of ideas for the software.

I don´t know how to manage the labels because I have no direct access to them.
is there another way?

Greetings, Alex

**Comment by timmwagener** [comment]
Very small but much anticipated fix :)
